version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    labels:
      - "Dependencies"
    schedule:
      interval: monthly
      timezone: US/Arizona
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "Dependencies"
    schedule:
      interval: monthly
      timezone: US/Arizona
    open-pull-requests-limit: 10
